language: elixir

elixir:
  - 1.2.0

otp_release:
  - 18.1

env: MIX_ENV=test

sudo: false

notifications:
  email: false

before_script:
  - apt-get install jq

script:
  - mix compile --warnings-as-errors
  - mix test
  - mix dogma
